image:
  file: .gitpod.Dockerfile
tasks:
  - name: Starting Project
    command:  cp .env.example .env &&
      sed -i "s|APP_URL=http://localhost:8000|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env &&
      sed -i "s/DB_HOST=mysql/DB_HOST=127.0.0.1/g" .env &&
      sed -i "s/REDIS_HOST=redis/REDIS_HOST=127.0.0.1/g" .env &&
      sed -i "s/DB_USERNAME=sail/DB_USERNAME=root/g" .env &&
      sed -i "s/DB_PASSWORD=password/DB_PASSWORD=/g" .env
      composer install &&
      php artisan key:generate &&
      php artisan badaso:setup &&
      php artisan storage:link &&
      npm install &&
      npm run dev &&
      mysql -u root -e "create database badaso" &&
      php artisan migrate &&
      php artisan db:seed --class="Database\Seeders\Badaso\BadasoSeeder" &&
      php artisan badaso:admin admin@admin.com --name=admin --username=admin --password=admin --confirm_password=admin --create
      php artisan serve
ports:
  - port: 8000
    onOpen: open-browser
  - port: 3306
  - port: 6379
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - PKief.material-icon-theme
    - bmewburn.vscode-intelephense-client
    - MehediDracula.php-namespace-resolver
    - junstyle.php-cs-fixer